
// This file contains mock AI functions that simulate AI-based analysis
// In a real application, these would be API calls to an actual AI backend

// Simulate a delay to mimic API call
const simulateApiDelay = () => new Promise((resolve) => setTimeout(resolve, 1500));

// Mock function for symptom analysis
export const mockAnalyzeSymptoms = async (symptoms: string) => {
  await simulateApiDelay();
  
  // This is mock data - in a real app, this would be generated by an AI model
  return {
    possibleConditions: [
      {
        name: "Common Cold",
        probability: 76,
        description: "A viral infection of the upper respiratory tract",
      },
      {
        name: "Seasonal Allergies",
        probability: 64,
        description: "An allergic response to environmental allergens",
      },
      {
        name: "Sinusitis",
        probability: 38,
        description: "Inflammation of the sinuses, often due to infection",
      },
    ],
    recommendation:
      "Based on your symptoms, it appears to be a common cold. Rest, stay hydrated, and take over-the-counter cold medications as needed. If symptoms worsen or persist beyond 7 days, please consult a doctor.",
    severity: 3, // Scale of 1-10
  };
};

// Mock function for image analysis
export const mockAnalyzeImage = async () => {
  await simulateApiDelay();
  
  // This is mock data - in a real app, this would be generated by an AI model
  return {
    diagnosis: "Eczema (Atopic Dermatitis)",
    confidence: 92,
    differential: [
      { condition: "Contact Dermatitis", probability: 45 },
      { condition: "Psoriasis", probability: 23 },
      { condition: "Fungal Infection", probability: 12 },
    ],
    recommendation:
      "The image shows characteristics consistent with eczema. Consider using an over-the-counter hydrocortisone cream and moisturize regularly. Avoid triggers like harsh soaps and extreme temperatures.",
    urgency: "low",
  };
};

// Mock function for health data analysis
export const mockAnalyzeHealthData = async (userId: string) => {
  await simulateApiDelay();
  
  // This is mock data - in a real app, this would be generated by an AI model
  return {
    insights: [
      "Your blood pressure has improved by 5% since last month",
      "Your sleep pattern shows improved quality compared to last week",
      "Consider increasing daily water intake based on urine color reports",
    ],
    recommendations: [
      "Continue with your current medication schedule",
      "Increase daily steps to 8,000 (currently averaging 6,700)",
      "Schedule a follow-up appointment in 3 months",
    ],
    warnings: [],
  };
};
