// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmzdcjovkaqyrjazknmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtemRjam92a2FxeXJqYXprbm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTM0MTcsImV4cCI6MjA2MDk4OTQxN30.DPww02z01Im7WUZ5CJ2fRgd26WDValGZqJ2RfMsXuvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);